language: python
sudo: false
env:
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py27-dj110
  - TOXENV=py27-djdev
  - TOXENV=py34-dj18
  - TOXENV=py34-dj19
  - TOXENV=py34-dj110
  - TOXENV=py34-djdev
matrix:
  allow_failures:
    - env: TOXENV=py27-djdev
    - env: TOXENV=py34-djdev
install:
  - pip install tox

script:
  - tox

#after_success:
#  - coverage combine
#  - codecov
